name: 'Contributing Check and Update'
description: 'Checks contributing file in calling repo and creates a PR if it''s outdated. If branch / PR already exists, will update and force push if necessary.'

inputs:
  branch:
    description: 'The branch to get the template file from'
    required: false
    default: 'main'
  contributing_update_dir:
    description: 'The directory path for contributing update'
    required: false
    default: 'contributing_update_temp'
  charm_path:
    description: 'The relative path to the charm in the repo'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v3'
    - name: 'Make temporary dir for this job'
      shell: bash
      run: |
        mkdir -p "${{ inputs.contributing_update_dir }}"
    - name: 'Download template file'
      shell: bash
      run: |
        wget -O "${{ inputs.contributing_update_dir }}/contributing.md.template" "https://raw.githubusercontent.com/canonical/kubeflow-ci/${{ inputs.branch }}/actions/contributing-update/contributing.md.template"
    - name: 'Generate and compare'
      id: generate-and-compare
      shell: bash
      run: |
        python ${{ github.action_path }}/src/generate_and_compare.py "${{ inputs.contributing_update_dir }}" "${{ inputs.charm_path }}"
    - name: 'Echo comparison_result'
      run: |
        echo "Comparison result is: ${{ steps.generate-and-compare.outputs.comparison_result }}"
      shell: bash
    - name: Generate branch suffix
      id: gen-branch-suffix
      shell: bash
      run: |
        transformed_path=$(echo "${{ inputs.charm_path }}" | sed 's/[^a-zA-Z]/-/g' | sed 's/-$//')
        echo "suffix=${transformed_path}" >> $GITHUB_OUTPUT
    - name: Move and Cleanup
      shell: bash
      run: |
        mv -f "${{ inputs.contributing_update_dir }}/contributing.md" "${{ inputs.charm_path }}/contributing.md"
        rm -rf "${{ inputs.contributing_update_dir }}"
    - name: 'Open PR'
      id: create-pull-request
      if: steps.generate-and-compare.outputs.comparison_result == '1'
      uses: peter-evans/create-pull-request@v6
      with:
        title: "(Automated) Update Contributing.md (${{ steps.gen-branch-suffix.outputs.suffix }})"
        body: "Updated contributing.md file based on auto-generate file from template"
        commit-message: "Updated contributing.md file based on auto-generate file from template"
        signoff: false
        delete-branch: true
        branch: "automated-update-contributing-${{ steps.gen-branch-suffix.outputs.suffix }}"      
