name: 'Get Charm Paths'
description: 'Emits a list of relative paths to charms in the repository'

inputs:
  base-dir:
    description: 'Base directory to search for charms'
    required: false
    default: './'
  charms-subdir:
    description: 'Subdirectory to search for charms'
    required: false
    default: 'charms'

outputs:
  charm-paths:
    description: 'JSON string of relative paths to charms in the repository'
    value: ${{ steps.get-charm-paths.outputs.charm_paths }}

runs:
  using: 'composite'
  steps:
    - uses: 'actions/checkout@v4'
    - name: 'Get paths for all charms in repo'
      id: get-charm-paths
      shell: bash
      run: python ${{ github.action_path }}/src/get_charm_paths.py ${{ inputs.base-dir }} --charms-subdir=${{ inputs.charms-subdir }}