# this CI is for internal import from another template
name: Pull Request

on:
  workflow_call:
    inputs:
      charm-path:
        required: true
        type: string
    secrets:
      CHARMHUB_TOKEN:
        required: true
jobs:
  lib-check:
    name: Check libraries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.2.3
        with:
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          charm-path: "${{ inputs.charm-path }}"
