name: Pull Request

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm we want to test/publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string
    secrets:
       CHARMHUB_TOKEN:
         required: true
jobs:
  quality-checks:
    name: Quality Checks
    uses: canonical/kubeflow-ci/.github/workflows/templates/_quality-checks.yaml@main
    secrets: inherit
    with:
      charm-path: ${{ inputs.charm-path }}
