name: 'Dump Charm Debug Artifacts'
description: 'Dumps to Artifacts useful Juju, Kubernetes, and Charmcraft log information.  Requires kubectl to be set up with a context, and charmcraft to be installed.'
inputs:
  artifact-prefix:
    description: "String used to prefix the uploaded artifact in order to ensure unique artifact names."
    required: false
runs:
  using: 'composite'
  steps:
    - name: Check out repo
      uses: actions/checkout@v3

    # Setup

    - name: Create artifact collection directory
      id: mkdir
      shell: bash
      run: |
        LOG_DIR="${LOGDUMP_OUTPUT_DIR:-tmp_logs_$GITHUB_JOB}"
        echo "log-dir=$(echo $LOG_DIR)" >> $GITHUB_OUTPUT
        mkdir $LOG_DIR

    - name: Export artifact prefix
      shell: bash
      run: |
        if [ -n "${{ inputs.artifact-prefix }}" ];
        then
          echo "prefix=${{ github.job }}-${{ inputs.artifact-prefix }}" >> "$GITHUB_ENV"
        else
          echo "prefix=${{ github.job }}" >> "$GITHUB_ENV"
        fi

    - name: Collect all logs
      shell: bash
      run: |
        touch ${{ steps.mkdir.outputs.log-dir }}/dummy.txt

    # Save logs
    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ env.prefix }}-juju-kubernetes-charmcraft-logs
        path: ${{ steps.mkdir.outputs.log-dir }}
        if-no-files-found: error
