name: 'Dump Charm Debug Artifacts'
description: 'Dumps to Artifacts useful Juju, Kubernetes, and Charmcraft log information.  Requires kubectl to be set up with a context, and charmcraft to be installed.'
runs:
  using: 'composite'
  steps:
    - name: Check out repo
      uses: actions/checkout@v3

    # Setup

    - name: Create artifact collection directory
      id: mkdir
      shell: bash
      run: |
        LOG_DIR="${LOGDUMP_OUTPUT_DIR:-tmp_logs_$GITHUB_JOB}"
        echo "log-dir=$(echo $LOG_DIR)" >> $GITHUB_OUTPUT
        mkdir $LOG_DIR

    # Dump logs

    - name: Collect all logs
      shell: bash
      run: |
        export OUTPUT_DIR=${{ steps.mkdir.outputs.log-dir }}
        bash ${{ github.action_path }}/logdump.bash

    # Save logs

    - name: Echo
      shell: bash
      run: |
        echo github.job.name
        echo ${{github.job.run_id}}
        echo github.job.run-name
        echo ${{github.job.run-name}}
        echo github.run-name
        echo ${{github.run-name}}
        echo github.action
        echo ${{github.action}}
        echo github.job
        echo ${{github.job}}
        echo github.run_number
        echo ${{github.run_number}}
        echo github.run_id
        echo ${{github.run_id}}
        echo github.job.run_id
        echo ${{github.job.run_id}}
        echo github.workflow
        echo ${{github.workflow}}
        echo "DONE"

    - name: Upload debug artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ github.job }}-${{github.run_id}}-juju-kubernetes-charmcraft-logs
        path: ${{ steps.mkdir.outputs.log-dir }}
        if-no-files-found: error
