name: Sync Github token to repos
on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'true/false whether to run action in dry-run mode'
        required: true
        default: 'true'
jobs:
  sync_github_token:
    runs-on: ubuntu-24.04
    steps:
      - uses: jpoehnelt/secrets-sync-action@7840777f242539d96b60477b66aa1c179e7644ea
        with:
          secrets: |
            ^GH_TOKEN$
          repositories: |
            ^canonical/katib-rocks
            ^canonical/pipelines-rocks
            ^canonical/kserve-rocks
            ^canonical/resource-dispatcher-rock
            ^canonical/feast-rocks
            ^canonical/kubeflow-rocks
            ^canonical/knative-rocks
            ^canonical/metacontroller-rock
            ^canonical/filebrowser-rock
            ^canonical/argo-workflows-rocks
            ^canonical/oidc-authservice-rock
            ^canonical/tensorflow-rock
            ^canonical/training-operator-rock
            ^canonical/dex-auth-rocks
            ^canonical/base-mlflow
            ^canonical/admission-webhook-operator$
            ^canonical/argo-operators$
            ^canonical/dex-auth-operator$
            ^canonical/envoy-operator$
            ^canonical/feast-operators$
            ^canonical/github-profiles-automator$
            ^canonical/istio-operators$
            ^canonical/katib-operators$
            ^canonical/kfp-operators$
            ^canonical/knative-operators$
            ^canonical/kserve-operators$
            ^canonical/kubeflow-dashboard-operator$
            ^canonical/kubeflow-profiles-operator$
            ^canonical/kubeflow-roles-operator$
            ^canonical/kubeflow-tensorboards-operator$
            ^canonical/kubeflow-trainer-operator$
            ^canonical/kubeflow-trainer-rocks$
            ^canonical/kubeflow-volumes-operator$
            ^canonical/metacontroller-operator$
            ^canonical/minio-operator$
            ^canonical/minio-rock$
            ^canonical/mlflow-operator$
            ^canonical/mlmd-operator$
            ^canonical/notebook-operators$
            ^canonical/oidc-gatekeeper-operator$
            ^canonical/pvcviewer-operator$
            ^canonical/request-authentication-configurator$
            ^canonical/resource-dispatcher$
            ^canonical/training-operator$
            ^canonical/training-operator-rocks$
            ^canonical/velero-integrator$
            ^canonical/velero-operator$
          dry_run: ${{ github.event.inputs.DRY_RUN }}
          github_token: ${{ secrets.GH_TOKEN }}
          concurrency: 10
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
