name: Sync GPG secrets to charm repos
on:
  workflow_dispatch:
    inputs:
      DRY_RUN:
        description: 'true/false whether to run action in dry-run mode'
        required: true
        default: 'true'
jobs:
  sync_gpg_secrets:
    runs-on: ubuntu-24.04
    steps:
      - uses: jpoehnelt/secrets-sync-action@7840777f242539d96b60477b66aa1c179e7644ea
        with:
          secrets: |
            ^GPG_PASSPHRASE$
            ^GPG_PRIVATE_KEY$
          repositories: |
            ^canonical/admission-webhook-operator$
            ^canonical/argo-operators$
            ^canonical/dex-auth-operator$
            ^canonical/envoy-operator$
            ^canonical/feast-operators$
            ^canonical/github-profiles-automator$
            ^canonical/istio-operators$
            ^canonical/katib-operators$
            ^canonical/kfp-operators$
            ^canonical/knative-operators$
            ^canonical/kserve-operators$
            ^canonical/kubeflow-dashboard-operator$
            ^canonical/kubeflow-profiles-operator$
            ^canonical/kubeflow-roles-operator$
            ^canonical/kubeflow-tensorboards-operator$
            ^canonical/kubeflow-volumes-operator$
            ^canonical/metacontroller-operator$
            ^canonical/minio-operator$
            ^canonical/mlflow-operator$
            ^canonical/mlmd-operator$
            ^canonical/notebook-operators$
            ^canonical/oidc-gatekeeper-operator$
            ^canonical/pvcviewer-operator$
            ^canonical/resource-dispatcher$
            ^canonical/training-operator$
          dry_run: ${{ github.event.inputs.DRY_RUN }}
          github_token: ${{ secrets.GH_TOKEN }}
          concurrency: 10
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
